SRC_FOLDER = src
SRC = $(SRC_FOLDER)/neighbor.C $(SRC_FOLDER)/spheres.C $(SRC_FOLDER)/box_reflecting.C $(SRC_FOLDER)/sphere.C $(SRC_FOLDER)/event.C $(SRC_FOLDER)/heap.C $(SRC_FOLDER)/read_input.C
generate_spheres : $(SRC)
	g++ $(SRC) -o data/generate_spheres
